#!/bin/sh

# 检查当前nf_conntrack_max值是否小于65536，若更小则修改
current_value=$(sysctl -n net.netfilter.nf_conntrack_max)
if [ "$current_value" -lt 65535 ]; then
    # 从sysctl.conf删除旧的nf_conntrack_max配置以避免重复
    sed -i '/nf_conntrack_max/d' /etc/sysctl.conf
    # 写入新配置，设置最大连接数为65535
    echo "net.netfilter.nf_conntrack_max = 65535" >>/etc/sysctl.conf
    # 应用配置并立即生效
    sysctl -p
fi

# 解除dropbear访问限制
if uci show dropbear | grep -q "DirectInterface"; then
    uci delete dropbear.main.DirectInterface
    uci commit dropbear
    /etc/init.d/dropbear restart
fi

# 清空当前系统所有的定时任务（Crontabs）
rm -f /etc/crontabs/root
touch /etc/crontabs/root

# 删除编译残留的 CoreMark 跑分检测脚本
rm -f /etc/coremark.sh

# =================================================================
# 1. config dnsmasq 优化参数
# =================================================================

# 清空旧配置，防止污染
uci -q delete dhcp.@dnsmasq[0].server
uci -q delete dhcp.@dnsmasq[0].extra_conf

# 开始设置 dnsmasq 主配置
uci set dhcp.@dnsmasq[0].domainneeded='1'
uci set dhcp.@dnsmasq[0].localise_queries='1'
uci set dhcp.@dnsmasq[0].rebind_protection='1'
uci set dhcp.@dnsmasq[0].rebind_localhost='1'
uci set dhcp.@dnsmasq[0].local='/lan/'
uci set dhcp.@dnsmasq[0].domain='lan'
uci set dhcp.@dnsmasq[0].expandhosts='1'
uci set dhcp.@dnsmasq[0].cachesize='10000'
uci set dhcp.@dnsmasq[0].authoritative='1'
uci set dhcp.@dnsmasq[0].readethers='1'
uci set dhcp.@dnsmasq[0].leasefile='/tmp/dhcp.leases'
uci set dhcp.@dnsmasq[0].localservice='1'
uci set dhcp.@dnsmasq[0].ednspacket_max='1232'
uci set dhcp.@dnsmasq[0].filter_aaaa='1'
uci set dhcp.@dnsmasq[0].no_ipv6='1'
uci set dhcp.@dnsmasq[0].dnsforwardmax='200'
uci set dhcp.@dnsmasq[0].min_cache_ttl='3600'
uci set dhcp.@dnsmasq[0].max_cache_ttl='86400'
uci set dhcp.@dnsmasq[0].noresolv='1'
uci set dhcp.@dnsmasq[0].ignore_hosts_dir='1'
uci set dhcp.@dnsmasq[0].allservers='1'
uci set dhcp.@dnsmasq[0].prefetch='1'
uci set dhcp.@dnsmasq[0].timeout='1'
uci set dhcp.@dnsmasq[0].retry='3'
uci set dhcp.@dnsmasq[0].nonegcache='1'

# 上游 DNS（列表用 add_list）
uci add_list dhcp.@dnsmasq[0].server='8.8.8.8'
uci add_list dhcp.@dnsmasq[0].server='223.5.5.5'

# =================================================================
# 2. config dhcp 'lan' 极致提效短租约调优
# =================================================================

# 强制覆盖局域网 DHCP 宣告服务，防止多拨或网络切换时终端设备残留死IP
uci -q set dhcp.lan=dhcp
uci -q set dhcp.lan.interface='lan'
uci -q set dhcp.lan.start='10'
uci -q set dhcp.lan.limit='200'
uci -q set dhcp.lan.leasetime='10m'
uci -q set dhcp.lan.dhcpv4='server'
uci commit dhcp
